version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: springboot
      POSTGRES_PASSWORD: prueba
      POSTGRES_DB: users
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
  mongodb:
    image: mongo:6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
  keycloak:
    image: quay.io/keycloak/keycloak:26.2.4
    restart: always
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://db:5432/users
      KC_DB_USERNAME: springboot
      KC_DB_PASSWORD: prueba
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev
    ports:
      - '8080:8080'
    depends_on:
      - db
volumes:
  db_data:
  mongo_data:
