apiVersion: v1
kind: Secret
metadata:
  name: user-service-secret

type: Opaque
data:
  DB_USERNAME: c3ByaW5nYm9vdA== # springboot
  DB_PASSWORD: cHJ1ZWJh # prueba
  RABBIT_USERNAME: Z3Vlc3Q= # guest
  RABBIT_PASSWORD: Z3Vlc3Q= # guest
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config

data:
  DB_URL: jdbc:postgresql://host.docker.internal:5432/userdb2
  RABBIT_HOST: host.docker.internal
  RABBIT_PORT: "5672"
  KEYCLOAK_ISSUER_URI: http://host.docker.internal:8080/realms/microservices
  KEYCLOAK_JWK_SET_URI: http://host.docker.internal:8080/realms/microservices/protocol/openid-connect/certs
  SERVER_PORT: "3000"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: user-service:0.0.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: user-service-config
                  key: DB_URL
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: user-service-secret
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: user-service-secret
                  key: DB_PASSWORD
            - name: RABBIT_HOST
              valueFrom:
                configMapKeyRef:
                  name: user-service-config
                  key: RABBIT_HOST
            - name: RABBIT_PORT
              valueFrom:
                configMapKeyRef:
                  name: user-service-config
                  key: RABBIT_PORT
            - name: RABBIT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: user-service-secret
                  key: RABBIT_USERNAME
            - name: RABBIT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: user-service-secret
                  key: RABBIT_PASSWORD
            - name: KEYCLOAK_ISSUER_URI
              valueFrom:
                configMapKeyRef:
                  name: user-service-config
                  key: KEYCLOAK_ISSUER_URI
            - name: KEYCLOAK_JWK_SET_URI
              valueFrom:
                configMapKeyRef:
                  name: user-service-config
                  key: KEYCLOAK_JWK_SET_URI
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: user-service-config
                  key: SERVER_PORT
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  type: NodePort
  selector:
    app: user-service
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 32000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: user-service-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: user-service.local
      http:
        paths:
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: user-service
                port:
                  number: 3000
